// Shrek the Musical KIDS - Complete Script Data
export const scriptData = {
  title: "Shrek the Musical KIDS",
  characters: [
    "STORYTELLER 1",
    "STORYTELLER 2",
    "STORYTELLER 3",
    "MAMA OGRE",
    "PAPA OGRE",
    "SHREK",
    "CAPTAIN OF THE GUARDS",
    "PINOCCHIO",
    "BIG BAD WOLF",
    "PIG #1",
    "PIG #2",
    "PIG #3",
    "WICKED WITCH",
    "PETER PAN",
    "UGLY DUCKLING",
    "FAIRY GODMOTHER",
    "PAPA BEAR",
    "MAMA BEAR",
    "BABY BEAR",
    "DONKEY",
    "PERFORMER",
    "LORD FARQUAAD",
    "GINGY",
    "YOUNG FIONA",
    "FIONA",
    "DRAGON",
    "ROOSTER",
    "BISHOP",
    "DWARF",
    "ALL",
    "GUARDS",
    "FAIRY-TALE CREATURES",
    "3 PIGS"
  ],
  scenes: [
    {
      number: 1,
      title: "Scene One",
      description: "The Ogre's Bog – Shrek's Childhood",
      lines: [
        { character: "STORYTELLER 1", text: "Once upon a time, there was a little ogre named Shrek, who lived with his parents in a bog by a tree." },
        { character: "STORYTELLER 2", text: "It was a pretty nasty place, but he was happy because ogres like nasty." },
        { character: "STORYTELLER 3", text: "On his birthday, the little ogre's parents sat him down to talk, just as all ogre parents had for hundreds of years before." },
        { type: "stage", text: "♪ SONG: BIG BRIGHT BEAUTIFUL WORLD — MAMA OGRE, PAPA OGRE, and YOUNG SHREK" },
        { character: "STORYTELLER 1", text: "And so the little ogre went off and found a muddy patch of swampland." },
        { character: "STORYTELLER 2", text: "Far, far away from the world that despised him." },
        { character: "STORYTELLER 3", text: "And there he stayed for many years, tucked away and all alone." },
        { type: "stage", text: "(SHREK enters.)" },
        { character: "SHREK", text: "Which is just the way I like it!" },
        { type: "stage", text: "♪ SONG: BIG BRIGHT BEAUTIFUL WORLD (reprise) — SHREK and STORYTELLERS" },
      ]
    },
    {
      number: 2,
      title: "Scene Two",
      description: "Shrek's Swamp – The Fairy-Tale Creatures Arrive",
      lines: [
        { type: "stage", text: "(GUARDS lead on a group of FAIRY-TALE CREATURES.)" },
        { character: "CAPTAIN OF THE GUARDS", text: "Right this way. Don't mind the mud. You'll get used to it." },
        { character: "PINOCCHIO", text: "This place is a dump!" },
        { character: "BIG BAD WOLF", text: "It's not fit for a pig!" },
        { character: "PIG #3", text: "Hello!" },
        { character: "PIG #2", text: "Vee can hear you!" },
        { character: "PIG #1", text: "Vee are standing right here!" },
        { character: "CAPTAIN OF THE GUARDS", text: "Look, you all read Lord Farquaad's decree." },
        { character: "PINOCCHIO", text: "Yeah, yeah, we read it. \"All fairy-tale creatures have been banished from the Kingdom of Duloc. All fruitcakes and freaks are hereby evicted.\"" },
        { character: "CAPTAIN OF THE GUARDS", text: "Alright, when I call your name, step forward." },
        { type: "stage", text: "♪ SONG: STORY OF MY LIFE — Various Characters" },
        { character: "CAPTAIN OF THE GUARDS", text: "Pinocchio!" },
        { character: "PINOCCHIO", text: "Oh, I'm not a puppet, I'm a real boy." },
        { character: "CAPTAIN OF THE GUARDS", text: "Anyone see the Gingerbread Man?" },
        { character: "CAPTAIN OF THE GUARDS", text: "Three Bears, take your spot over there by that sign. No, that's too far. Too close. Ahh, just right. Wicked Witch!" },
        { character: "CAPTAIN OF THE GUARDS", text: "Ugly Duckling!" },
        { character: "CAPTAIN OF THE GUARDS", text: "Three Pigs!" },
        { character: "CAPTAIN OF THE GUARDS", text: "And remember, if we find you back in the kingdom, you will be executed." },
        { type: "stage", text: "(SHREK returns from an errand.)" },
        { character: "SHREK", text: "What are you doing in my swamp?" },
        { character: "PINOCCHIO", text: "Well gosh, we were forced to come here." },
        { character: "PIG #2", text: "By Lord Farquaad! He hoofed und he poofed, und he signed an eveection notice." },
        { character: "SHREK", text: "Well, not my problem." },
        { character: "MAMA BEAR", text: "We can't go back!" },
        { character: "PIG #1", text: "Farquaad vill turn us into bratvurst!" },
        { character: "BIG BAD WOLF", text: "The guy's bad news." },
        { character: "PIG #3", text: "Hey, maybe you could talk to him." },
        { character: "BABY BEAR", text: "Yeah, he'll listen to you! You're big and scary." },
        { character: "SHREK", text: "I'm also an ogre, which means I stay on my swamp and avoid large crowds." },
        { character: "WICKED WITCH", text: "Look here, ogre, I'm gonna spell it out for ya. You're the only one tough enough to stand up to that no-good flim-flammer Farquaad." },
        { character: "SHREK", text: "Okay, fine, I get it! Attention all... fairy-tale things! I'm gonna go see this Farquaad guy right now, and get you all off my land and back where you came from!" },
      ]
    },
    {
      number: 3,
      title: "Scene Three",
      description: "On the Road – Shrek Meets Donkey",
      lines: [
        { type: "stage", text: "(DONKEY runs in, being chased by GUARDS.)" },
        { character: "DONKEY", text: "Ahhhhhhhhhh! I'm being chased by goons! Help a donkey out, wouldja?" },
        { type: "stage", text: "(DONKEY hides behind SHREK. GUARDS stop in their tracks when they see SHREK.)" },
        { character: "GUARDS", text: "Ahhhhhhh!" },
        { type: "stage", text: "♪ SONG: SHREK (I'm a Believer) — SHREK and DONKEY" },
        { character: "CAPTAIN OF THE GUARDS", text: "Shrek! Donkey! By the order of Lord Farquaad, I am authorized to place you both under arrest." },
        { character: "SHREK", text: "Under arrest, eh? ... Boo." },
        { type: "stage", text: "(The GUARDS freeze in fear, knees shaking.)" },
        { character: "GUARDS", text: "Ahhhhhhh!" },
        { character: "SHREK", text: "This is the part where you run away." },
        { type: "stage", text: "(The GUARDS run screaming.)" },
        { character: "SHREK", text: "And don't come back! Now, which way to Duloc..." },
        { character: "DONKEY", text: "Oh Duloc! I know Duloc! You gotta let me show you the way, because I am like a GPS with fur!" },
        { character: "SHREK", text: "Alright, look, only because I'm lost, you can come—" },
        { character: "DONKEY", text: "Yeah! Woo-hoo, alright—!" },
        { character: "SHREK", text: "On one condition! You keep the jabbering to a minimum." },
        { character: "DONKEY", text: "You got it! No jabbering! Man, you will not regret this." },
        { character: "SHREK", text: "Too late." },
        { character: "DONKEY", text: "Now that's what I'm talking about! Shrek and Donkey, two stalwart friends off on a whirlwind big-city adventure!" },
      ]
    },
    {
      number: 4,
      title: "Scene Four",
      description: "Duloc – Lord Farquaad's Kingdom",
      lines: [
        { type: "stage", text: "♪ SONG: WHAT'S UP, DULOC? — DULOC PERFORMERS" },
        { character: "PERFORMER", text: "And here's the man who made it happen! That towering colossus of moxie! Loooooooooord Farquaad!" },
        { type: "stage", text: "♪ Broad fanfare music. LORD FARQUAAD enters." },
        { character: "LORD FARQUAAD", text: "Oh, it's you! What a terrific surprise! And lucky you, you're here at torture time! Bring in the cookie!" },
        { type: "stage", text: "(Farquaad's GUARDS bring GINGY onstage.)" },
        { character: "GINGY", text: "No! No! I won't speak! I won't! You monster!" },
        { character: "LORD FARQUAAD", text: "I'm not the monster here, you are. You and the rest of that fairy-tale riffraff!" },
        { type: "stage", text: "(FARQUAAD reaches for GINGY's buttons.)" },
        { character: "GINGY", text: "Okay!... I'll tell you. She's a day's walk from here. In a dragon-guarded castle, surrounded by hot, boiling lava. In the highest room in the tallest tower, you'll find a fiery redhead named Princess Fiona." },
        { character: "LORD FARQUAAD", text: "Ooo, Princess Fiona. She sounds perfect. Except for that dragon and lava thing. I'll have to find someone else to go..." },
        { character: "GINGY", text: "Big surprise." },
        { character: "LORD FARQUAAD", text: "Captain, take the cookie to the swamp with the rest of the fairy-tale freaks!" },
        { character: "GINGY", text: "Swamp?! That's the thanks I get?!" },
        { type: "stage", text: "(GUARDS take GINGY offstage.)" },
        { character: "SHREK", text: "Look, I'll be out of your silky hair just as soon as you gimme my swamp back." },
        { character: "LORD FARQUAAD", text: "Your swamp?" },
        { character: "SHREK", text: "Yes, where you dumped those fairy-tale creatures." },
        { character: "LORD FARQUAAD", text: "Wait a minute. Wait... a... minute. Oh this is too perfect. People of Duloc, we have a winner!" },
        { character: "ALL", text: "Hooray!" },
        { character: "LORD FARQUAAD", text: "Congratulations, ogre! You've won the honor of embarking on a great and noble quest!" },
        { character: "DONKEY", text: "But, we're already on a quest." },
        { character: "SHREK", text: "To get my swamp back." },
        { character: "LORD FARQUAAD", text: "Yes, and you've nearly accomplished it! All you need to do is rescue Princess Fiona from the dragon, bring her to me to marry, and I'll hand over your swamp!" },
        { type: "stage", text: "(FARQUAAD and DULOCIANS vanish. SHREK and DONKEY find themselves outside the gates of Duloc.)" },
        { character: "DONKEY", text: "I don't get it. Why didn't you just make Farquaad give you your swamp back? You know, pull some of that ogre stuff on him?" },
        { character: "SHREK", text: "For your information, there's a lot more to ogres than people think. Ogres are like onions." },
        { character: "DONKEY", text: "They stink? They make you cry?" },
        { character: "SHREK", text: "No! Layers. Onions have layers. Ogres have layers. We both have layers!" },
        { character: "DONKEY", text: "Ohhhh, you both have layers. You know... not everybody likes onions." },
        { character: "SHREK", text: "Come on. Let's go rescue the princess." },
      ]
    },
    {
      number: 5,
      title: "Scene Five",
      description: "Fiona's Tower – The Princess Waits",
      lines: [
        { type: "stage", text: "♪ SONG: I KNOW IT'S TODAY — YOUNG FIONA, TEEN FIONA, ADULT FIONA" },
        { character: "YOUNG FIONA", text: "It's story time. Settle in, girls..." },
        { type: "stage", text: "(YOUNG FIONA sings, becomes TEEN FIONA, then ADULT FIONA. All three join together.)" },
      ]
    },
    {
      number: 6,
      title: "Scene Six",
      description: "The Dragon's Keep & Fiona's Tower",
      lines: [
        { character: "SHREK", text: "Hey look, the dragon's keep! We're here." },
        { character: "DONKEY", text: "Whew! Shrek! Was that you? Man! You gotta warn somebody before you just crack one off! My mouth was open and everything!" },
        { character: "SHREK", text: "Believe me, Donkey, if it was me you'd be dead. It's brimstone. Oh, hey, this'll come in handy. Hope it's fireproof. Alright, now you wait here and I'll be back in a bit." },
        { type: "stage", text: "(SHREK exits. DONKEY wanders farther into the Dragon's keep.)" },
        { character: "DONKEY", text: "Shreeeekkk..." },
        { type: "stage", text: "(DRAGON appears! DONKEY runs off screaming.)" },
        { type: "stage", text: "(Fiona's tower. FIONA is singing.)" },
        { character: "FIONA", text: "I KNOW IT'S TODAY... OO-OO-OOO-OOO" },
        { character: "SHREK", text: "Helloooo! Anyone up there?!" },
        { type: "stage", text: "(SHREK shakes FIONA awake.)" },
        { character: "FIONA", text: "Uhl-uhl-uhl!" },
        { character: "SHREK", text: "Are you Princess Fiona?" },
        { character: "FIONA", text: "I am. Awaiting a knight so bold as to rescue me." },
        { character: "SHREK", text: "Ah, that's nice. Now let's go." },
        { character: "FIONA", text: "But wait, Sir Knight! I have long awaited this day! And I would'st first like to knowest the name of my champion." },
        { character: "SHREK", text: "Um... Shrek." },
        { character: "FIONA", text: "Sir Shrek... You didn't slay the dragon?" },
        { character: "SHREK", text: "It's on my to-do list. Come on!" },
        { type: "stage", text: "(FIONA and SHREK climb down. DONKEY runs across.)" },
        { character: "SHREK", text: "Donkey!" },
        { character: "DONKEY", text: "Shrek!" },
        { character: "FIONA", text: "Dragon!" },
        { character: "ALL", text: "Run!" },
        { type: "stage", text: "♪ DRAGON CHASE — They escape and SHREK removes his helmet." },
        { character: "DONKEY", text: "Did you see that?" },
        { character: "FIONA", text: "You did it! You-did-it-you-did-it-you-did-it. Sir Shrek, the battle is won. A princess is rescued by a brave knight and then they share true love's first kiss." },
        { character: "DONKEY", text: "Hahahahaha!" },
        { character: "FIONA", text: "What is so funny? Take off the helmet." },
        { character: "FIONA", text: "Take it off!" },
        { character: "SHREK", text: "No!" },
        { character: "FIONA", text: "Now!" },
        { character: "SHREK", text: "Okay! Easy. As you command, Your Highness..." },
        { character: "FIONA", text: "You're... an ogre?" },
        { character: "SHREK", text: "Oh, you were expecting Prince Charming?" },
        { character: "FIONA", text: "Well... yes actually. Oh, no! I'm supposed to be rescued by my true love! Not by some ogre and his... pet." },
        { character: "SHREK", text: "Princess, I was sent to rescue you by Lord Farquaad, okay? He's the one who wants to marry you." },
        { character: "FIONA", text: "Oh. So, tell me about my groom-to-be, Lord Farquaad. What's he like?" },
        { character: "SHREK", text: "Well, let me put it this way, Princess - men of Farquaad's stature are in short supply." },
        { character: "FIONA", text: "Alright, yuck it up. Doesn't bother me. Not today. After a lifetime of misery, things are finally going my way." },
        { character: "SHREK", text: "I'm sure it was very difficult living in a dragon-guarded tower." },
        { character: "FIONA", text: "It was." },
        { character: "FIONA", text: "You're not actually comparing yourself to what I endured?" },
        { character: "SHREK", text: "I'm just saying you don't corner the market on unhappy childhoods." },
        { type: "stage", text: "♪ SHREK farts, then FIONA burps. They laugh. SONG: MAKE A MOVE (Donkey)" },
        { character: "SHREK", text: "Donkey!!!" },
        { character: "DONKEY", text: "Oh, sorry, I just got caught up in the magic of the night! The fireflies, that beautiful sunset..." },
        { character: "FIONA", text: "Sunset?! Oh my gosh! Sunset! Oh no!! I mean... it's late. It's very late." },
        { character: "SHREK", text: "What?" },
        { character: "FIONA", text: "I'm sorry, but I have to go." },
        { character: "SHREK", text: "Oh. Alright." },
        { character: "FIONA", text: "Good night." },
        { character: "SHREK", text: "Good night." },
        { type: "stage", text: "(FIONA enters the barn. DONKEY turns to SHREK.)" },
        { character: "DONKEY", text: "Uh-uh. No, sir. I'm sorry, but I did not come this whole way, puttin' up with you and your body odor, just so you can let her walk away like that!" },
        { character: "SHREK", text: "I'm just bringing her back to Farquaad." },
        { character: "DONKEY", text: "Uh-huh. So you don't have any feelings for her at all?" },
        { character: "SHREK", text: "Look, even if I did... and I'm not saying I do, 'cause I don't. She's a princess and I'm..." },
        { character: "DONKEY", text: "An ogre?" },
        { character: "SHREK", text: "Yeah. An ogre." },
        { character: "DONKEY", text: "She needs to know what you're feelin'..." },
        { character: "SHREK", text: "Where are you going?" },
        { character: "DONKEY", text: "To get more firewood. Before your fire dies." },
        { type: "stage", text: "♪ SONG: NIGHT ARIA. DONKEY exits, then re-enters with firewood." },
        { character: "DONKEY", text: "Shrek, did you see that sunset. Man, it's dark out here. Shrek? Ooooh! Maybe he's talking to the princess? I'll just see if they're in the barn... together. Shrek? Princess Fiona? It's very spooky in here, I ain't playing no games..." },
        { type: "stage", text: "(DONKEY comes face to face with FIONA, now an ogress.)" },
        { character: "DONKEY", text: "Ahhhhhhhhhhh!" },
        { character: "FIONA", text: "Ahhhhhhhhhh!" },
        { character: "DONKEY", text: "Princess...? What happened to you?" },
        { character: "FIONA", text: "It's a curse. I've had it since I was a girl." },
        { character: "DONKEY", text: "A curse?" },
        { character: "FIONA", text: "A witch cast a spell on me. So now every night, when the sun goes down, I become this... this horrible, ugly beast!" },
        { character: "DONKEY", text: "Wait a second, this is perfect!" },
        { character: "FIONA", text: "Perfect?! Donkey, if Lord Farquaad finds out I look like this, he'll never marry me!" },
        { character: "DONKEY", text: "So?" },
        { character: "FIONA", text: "So, I have to kiss my true love! The kiss is the only thing that will break the spell and make me beautiful." },
        { character: "DONKEY", text: "But you know... umm, you're kind of an ogre, and Shrek... well, you've got a lot in common." },
      ]
    },
    {
      number: 7,
      title: "Scene Seven",
      description: "The Next Morning – Feelings & Freak Flag",
      lines: [
        { type: "stage", text: "(The next morning. A rooster crows.)" },
        { character: "ROOSTER", text: "Cock-a-doodle-doo!" },
        { type: "stage", text: "♪ SONG: MORNING. FIONA sings, looking for SHREK." },
        { character: "FIONA", text: "Shrek! Thank goodness! There's something I have to tell you..." },
        { character: "SHREK", text: "You don't have to tell me anything. I heard enough last night." },
        { character: "FIONA", text: "Oh. You... you heard what I said?" },
        { character: "SHREK", text: "Every word. Especially \"who could love such a hideous, ugly beast?!\"" },
        { character: "FIONA", text: "But... I thought that wouldn't matter to you." },
        { character: "SHREK", text: "Yeah, well it does." },
        { type: "stage", text: "(FARQUAAD enters on a broomstick horse.)" },
        { character: "LORD FARQUAAD", text: "I am Lord Farquaad. Princess Fiona, I ask your hand in marriage. Will you be the perfect bride for the perfect groom?" },
        { character: "FIONA", text: "Lord Farquaad... I accept. Let's get married today. Before sunset." },
        { character: "LORD FARQUAAD", text: "Oh! Anxious, are we? You're right. The sooner the better. We'll be married by sunset!" },
        { type: "stage", text: "(DONKEY enters, stretching.)" },
        { character: "DONKEY", text: "Oh man, there's nothing like a good night's sleep. What I miss?" },
        { character: "FIONA", text: "Fare thee well, ogre." },
        { type: "stage", text: "(FIONA and FARQUAAD exit.)" },
        { character: "DONKEY", text: "Shrek! What are you doing? You're letting her get away! Look! There's something you don't know. I talked to her last night and—" },
        { character: "SHREK", text: "I heard you two talking last night. She said I was a hideous creature." },
        { character: "DONKEY", text: "She wasn't talking about you!" },
        { character: "SHREK", text: "She wasn't talking about me? Well then who was she talking about?" },
        { character: "DONKEY", text: "She's the princess who loves him." },
        { character: "SHREK", text: "Loves me? She said I was ugly! A hideous creature! I heard you two talking." },
        { character: "DONKEY", text: "She wasn't talking about you!" },
        { character: "SHREK", text: "I'm just bringing her back to Farquaad." },
        { character: "DONKEY", text: "But Shrek, I want to go home with you." },
        { character: "SHREK", text: "Me? No! I live alone! My swamp, me. Nobody else, understand? Nobody! Especially useless — pathetic — annoying — talking donkeys!" },
        { character: "DONKEY", text: "But - I thought—" },
        { character: "SHREK", text: "Yeah, well you know what? You thought wrong." },
        { type: "stage", text: "(Fairy-tale creatures return to swamp.)" },
        { character: "PINOCCHIO", text: "Just when ya think life can't get any worse, ya get evicted from a swamp!" },
        { character: "BIG BAD WOLF", text: "Well, look who it is!" },
        { character: "MAMA BEAR", text: "I thought you were going to help us." },
        { character: "BABY BEAR", text: "Instead, you had us kicked out!" },
        { character: "SHREK", text: "Well, what did you expect from an ogre?!" },
        { character: "PETER PAN", text: "We believed in you!" },
        { character: "SHREK", text: "Aw, grow up!" },
        { character: "PETER PAN", text: "I won't grow up!" },
        { character: "SHREK", text: "Then get out of my way." },
        { character: "DONKEY", text: "Well, there he goes again. Pushing everyone away. Just like he did to me. Just like he did to Fiona. You're so wrapped up in layers, onion boy, you're afraid of your own feelings!" },
        { character: "UGLY DUCKLING", text: "Who's Fiona?" },
        { character: "SHREK", text: "My... nothing." },
        { character: "DONKEY", text: "Ohhh, now he's interested. Two minutes ago he was all, \"Don't talk to me! Go away! I don't need anybody!\"" },
        { character: "SHREK", text: "Look, I'm sorry. I guess I am just a big stupid ogre. Which is why the princess and I can never be together." },
        { character: "GINGY", text: "Listen up, ogre!" },
        { type: "stage", text: "♪ SONG: FREAK FLAG — All creatures" },
        { character: "BIG BAD WOLF", text: "The way they think, that is." },
        { character: "BABY BEAR", text: "That's right, Wolfie!" },
        { character: "SHREK", text: "My what?" },
        { character: "PINOCCHIO", text: "Let your freak flag fly!" },
        { character: "ALL", text: "Yeah!" },
        { character: "SHREK", text: "I'm green! I'm mean! Get used to it!" },
        { character: "SHREK", text: "Donkey! The wedding!" },
        { character: "DONKEY", text: "Ha! I have a plan! Gather around!" },
        { character: "ALL", text: "To Duloc!" },
      ]
    },
    {
      number: 8,
      title: "Scene Eight",
      description: "Duloc Cathedral – The Wedding & True Love",
      lines: [
        { type: "stage", text: "♪ SONG: WEDDING PROCESSION — Cathedral. BISHOP, GUARDS, FIONA, and FARQUAAD enter." },
        { character: "BISHOP", text: "People of Duloc, we gather here today to bear witness to the union of our new king and queen—" },
        { character: "FIONA", text: "Um... Excuse me... ah... Could we just skip to the \"I do's\"?" },
        { character: "BISHOP", text: "Right, well then. Uh, do you, Lord Farquaad, take Princess Fiona?" },
        { character: "LORD FARQUAAD", text: "I do." },
        { type: "stage", text: "(SHREK bursts down the aisle.)" },
        { character: "SHREK", text: "Stop the wedding! Fiona - I need to talk to you." },
        { character: "FIONA", text: "Oh, now you want to talk? Well it's a little late for that." },
        { character: "SHREK", text: "You can't marry him!" },
        { character: "FIONA", text: "And why not?" },
        { character: "SHREK", text: "He's not your true love. I—" },
        { character: "LORD FARQUAAD", text: "Booooooooooooo! Are we ready, darling?" },
        { character: "FIONA", text: "I can't." },
        { type: "stage", text: "(FIONA rushes off.)" },
        { character: "PINOCCHIO", text: "That's it! We've taken your abuse for the last time, Farquaad! We demand our homes back!" },
        { character: "FAIRY-TALE CREATURES", text: "Yeah! The guy is a sham! He'll pay! Up with fairies! Power to the cookies!" },
        { character: "DWARF", text: "I suppose my invitation was lost in the mail?" },
        { character: "LORD FARQUAAD", text: "Well maybe if you hadn't abandoned me in the woods?" },
        { character: "DWARF", text: "Abandoned you? You were twenty-eight, and living in my basement!" },
        { character: "PINOCCHIO", text: "People of Duloc, your leader is a Halfling!" },
        { character: "MAMA BEAR", text: "Which is a lovely thing to be!" },
        { character: "LORD FARQUAAD", text: "I'm a king! I'm a big man! A big, tall, giant man with a kingdom! Not-a-freak! Not a freak! I have a castle!" },
        { type: "stage", text: "(FIONA enters with a lantern, illuminating her face.)" },
        { character: "FIONA", text: "Stop the wedding!" },
        { type: "stage", text: "(The crowd turns and gasps! FIONA has transformed into an ogress.)" },
        { character: "LORD FARQUAAD", text: "Fiona?" },
        { character: "FIONA", text: "I wanted to show you before." },
        { character: "SHREK", text: "Well, ah... that explains a lot." },
        { character: "SHREK", text: "No actually, you won't. I'd like you to meet a friend of mine." },
        { type: "stage", text: "(DRAGON enters. Flames circle FARQUAAD and he disappears.)" },
        { character: "DONKEY", text: "All hail the dragon!" },
        { character: "ALL", text: "Yay! To the dragon!" },
        { character: "DONKEY", text: "Oooh! Y'all got to watch this! Now that she and Shrek kissed, she's gonna change back into a beautiful princess. You just wait and see. This is gonna be crazy!!! Tell 'em the poetry — tell 'em the poetry!" },
        { character: "FIONA", text: "You were saying?" },
        { character: "SHREK", text: "I'm your true love, Fiona." },
        { character: "FIONA", text: "Yeah I know, and I'm yours." },
        { character: "STORYTELLER 2", text: "Until you find true love's first kiss—" },
        { character: "STORYTELLER 3", text: "And then take love's true form!" },
        { character: "ALL", text: "True form... true form... true form..." },
        { type: "stage", text: "(The CROWD reveals FIONA, still an ogress.)" },
        { character: "SHREK", text: "Fiona... are you alright?" },
        { character: "FIONA", text: "Well, yes... but... I don't understand. I'm supposed to be beautiful." },
        { character: "SHREK", text: "But you are beautiful." },
        { type: "stage", text: "♪ SONG: FINALE" },
        { character: "SHREK", text: "And that is how the little ogre came to live on the swamp with a beautiful princess." },
        { character: "DONKEY", text: "And his best friend." },
        { character: "SHREK", text: "And his best friend." },
        { character: "GINGY", text: "And a Gingerbread Man!" },
        { character: "PINOCCHIO", text: "And a very handsome puppet!" },
        { character: "SHREK", text: "Okay..." },
        { character: "UGLY DUCKLING", text: "And an Ugly Duckling!" },
        { character: "WICKED WITCH", text: "And a Witch!" },
        { character: "BIG BAD WOLF", text: "And a Big Bad Wolf!" },
        { character: "3 PIGS", text: "The Three Pigs!" },
        { character: "GINGY", text: "God bless us! Every one!" },
        { character: "ALL", text: "The End!" },
      ]
    }
  ]
};

export const characterEmoji = {
  "SHREK": "🟢",
  "DONKEY": "🫏",
  "FIONA": "👸",
  "YOUNG FIONA": "👧",
  "LORD FARQUAAD": "👑",
  "PINOCCHIO": "🪵",
  "GINGY": "🍪",
  "BIG BAD WOLF": "🐺",
  "MAMA BEAR": "🐻",
  "BABY BEAR": "🐻",
  "PAPA BEAR": "🐻",
  "WICKED WITCH": "🧙‍♀️",
  "PETER PAN": "🧚",
  "UGLY DUCKLING": "🦆",
  "DRAGON": "🐲",
  "STORYTELLER 1": "📖",
  "STORYTELLER 2": "📖",
  "STORYTELLER 3": "📖",
  "CAPTAIN OF THE GUARDS": "⚔️",
  "BISHOP": "⛪",
  "DWARF": "🎭",
  "ROOSTER": "🐓",
  "MAMA OGRE": "👹",
  "PAPA OGRE": "👹",
  "FAIRY GODMOTHER": "✨",
  "PERFORMER": "🎭",
  "GUARDS": "⚔️",
  "ALL": "🎭",
  "PIG #1": "🐷",
  "PIG #2": "🐷",
  "PIG #3": "🐷",
  "3 PIGS": "🐷",
  "FAIRY-TALE CREATURES": "🧚",
};
